full_name = 'satoshi nakamoto'  # capitalize(), title()
print(full_name.capitalize())
print(full_name.title())
state = 'mississippi'  # count('ss'), count('pp'), count('ppp')
print(state.count('ss'))
print(state.count('pp'))
print(state.count('ppp'))
url = 'www.python.orgw'  # startswith('ww'), endswith('g'), endswith('.py'), strip('w'), rstrip('w'), lstrip('w')
print(url.startswith('ww'))
print(url.endswith('g'))
print(url.endswith('.py'))
print(url.strip('w'))
print(url.rstrip('w'))
print(url.lstrip('w'))
sentence = 'I saw a saw saw'  # find('saw'), rfind('saw'), find('jeje'), index('saw'), rindex('saw'), index('jeje')
print(sentence.find('saw'))
print(sentence.rfind('saw'))
print(sentence.find('jeje'))
print(sentence.index('saw'))
print(sentence.rindex('saw'))
# print(sentence.index('jeje'))
func = '5tAn(x)'  # upper(), lower(),
print(func.upper())
print(func.lower())
swap = 'AAAhhHaAhh'  # swapcase()
print(swap.swapcase())
song = 'LUMBERJACK'  # isupper(), islower()
print(song.isupper())
print(song.islower())
string = "I'm bad in Python"  # replace('bad', 'good')
print(string.replace('bad', 'good'))
e = '2.71828'  # isalnum(), isalpha(), isdecimal(), isdigit(), isnumeric()
print(e.isalnum())
print(e.isalpha())
print(e.isdecimal())
print(e.isdigit())
print(e.isnumeric())
num = 18055  # isalnum(), isalpha(), isdecimal(), isdigit(), isnumeric()
num = str(num)
print(num.isalnum())
print(num.isalpha())
print(num.isdecimal())
print(num.isdigit())
print(num.isnumeric())
# Create a string where the istitle() method returns True
s1 = 'Hola Mundo Soy Daniel'
print(s1.istitle())
# Create a string where the isspace() method returns True
s2 = 'Hola Mundo Soy Daniel'
print(s2.isspace())
# Create a string where you can use removeprefix() and removesuffix(). Hint: use a URL
url = ' www.python.orgw '
print(url.removeprefix())
print(url.removesuffix())
# Create a valid object where you can use split() method
s3 = 'Hola Mundo Soy Daniel'
print(s3.split())